# Generated by Django 3.1.6 on 2021-02-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaliSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('endereco', models.CharField(max_length=30, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=40, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('phone', models.IntegerField(max_length=15, verbose_name='Telefone')),
            ],
        ),
    ]
