# Generated by Django 3.1.6 on 2021-02-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaliSite', '0003_auto_20210207_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=20, verbose_name='Cliente')),
                ('produto', models.CharField(max_length=20, verbose_name='Produto')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('data', models.DateField(verbose_name='Data')),
                ('email', models.EmailField(max_length=80, verbose_name='Email')),
                ('fone', models.IntegerField(verbose_name='Telefone')),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='fone',
        ),
        migrations.AlterField(
            model_name='product',
            name='estoque',
            field=models.IntegerField(blank=True, default=0, verbose_name='Qtdade em Estoque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, verbose_name='Preço'),
        ),
    ]
