# Generated by Django 3.1.6 on 2021-02-12 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaliSite', '0004_auto_20210212_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='endereco',
            field=models.CharField(max_length=100, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cliente',
            field=models.CharField(max_length=100, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='produto',
            field=models.CharField(max_length=100, verbose_name='Produto'),
        ),
    ]
